<a href="https://colab.research.google.com/github/20ujjwal/assignment-1/blob/main/ujjwal_joshi_202301068_7_02_2024_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr1=np.array([1, 2, 3, 6, 4, 5])
arr2=np.flip(arr1)
print(arr2)

[5 4 6 3 2 1]


In [ ]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

print("arr1:")
print(arr1)

print("arr2:")
print(arr2)

arr1:
[[1 2]
 [3 4]]
arr2:
[[1 2]
 [3 4]]


In [ ]:
import numpy as np
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
soae= np.sum(gfg)
soaerw=np.sum(gfg,axis=1)
soaecw=np.sum(gfg,axis=0)
print("Sum of all elements:", soae)
print("Sum of all elements row-wise",soaerw)
print("Sum of all elements column-wise",soaecw)

Sum of all elements: 45
Sum of all elements row-wise [[14]
 [16]
 [15]]
Sum of all elements column-wise [[20  9 16]]


In [ ]:
import numpy as np
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
most_frequent_value1, counts1 = np.unique(x, return_counts=True)
most_frequent_value2, counts2 = np.unique(y, return_counts=True)
most_frequent_index1 = np.where(x == most_frequent_value1[counts1.argmax()])[0]
most_frequent_index2 = np.where(y == most_frequent_value2[counts2.argmax()])[0]
print("Most frequent value:", most_frequent_value1[counts1.argmax()])
print("Indices:", most_frequent_index1)
print("Most frequent value:", most_frequent_value2[counts2.argmax()])
print("Indices:", most_frequent_index2)

Most frequent value: 1
Indices: [0 5 7 8 9]
Most frequent value: 1
Indices: [0 1 2]
